name: Bug Report
description: File a bug report
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve Webcomponent.dev! :rocket:
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: |
        Please provide reproduction steps so we can properly investigate the issue :pray:
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Link to the component
      description: "Observing the issue directly in your component will always help us provide faster feedback :+1:"
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      description: It may help us identify the problem
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true
