blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/divriots/webcomponents.dev/discussions/new?category=ideas
    about: "Suggest ideas using our discussion forums"
